github:
  organisations:
  - name: activiti 
    repositories:
    - name: activiti-api
      branch: develop
    - name: activiti
      branch: develop
    - name: activiti-dependencies
      branch: develop
      useSinglePullRequest: true
    - name: activiti-cloud-build
      branch: develop
