github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-examples
      branch: master
    - name: activiti-cloud-runtime-bundle-service
      branch: develop
      useSinglePullRequest: true
