github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-dependencies
      branch: develop
      useSinglePullRequest: true
    - name: activiti
      branch: develop
    - name: activiti-cloud-service-common
      branch: develop
