github:
  organisations:
  - name: activiti 
    repositories:
    - name: activiti-dependencies
      branch: develop
    - name: activiti
      branch: develop
    - name: activiti-cloud-api
      branch: develop