github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-examples
      branch: master
    - name: activiti-cloud-runtime-bundle-service
      branch: develop
      useSinglePullRequest: true
    - name: activiti-cloud-service-common
      branch: develop
      useSinglePullRequest: true
    - name: activiti-cloud-api
      branch: develop
      useSinglePullRequest: true
    - name: activiti-cloud-process-model-service
      branch: develop
      useSinglePullRequest: true
      
